### ISSUE TITLE
com.fasterxml.jackson.databind.exc.ValueInstantiationException on API Error

### ISSUE THREAD

**Issue by TheCycoONE** [sinch/sinch-java-sms#44]
Sinch SDK Version: 2.2.1
JDK: Amazon Corretto (OpenJDK) 17
Framework: Spring Boot 2.7.18

Seeing this error occasionally. Possibly related to sending to a number that is still provisioning but I'm not sure of that. At the moment I don't have any further information but if I'm able to get a packet capture I'll paste the response that triggers the error here.

```
com.sinch.xms.ConcurrentException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.sinch.xms.api.ApiErrorImpl`, problem: code
 at [Source: (ByteArrayInputStream); line: 1, column: 128]
 ```

**Comment by thomasf147** [comment]
Thank you for a very detailed report, we will look into it
